#!/bin/sh

DAEMON="/usr/bin/aesdsocket"
DAEMON_NAME="aesdsocket"
DAEMON_OPTS="-d"
PIDFILE="/var/run/$DAEMON_NAME.pid"
DESC="assignments 5 aesd Socket Daemon"


case "$1" in
  start)
    echo "Starting $DESC..."
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
    ;;
  stop)
    echo "Starting $DESC..."
    start-stop-daemon --stop --pidfile $PIDFILE --name $NAME --signal SIGTERM
    rm -f $PIDFILE
    ;;
  restart)
    echo "Restarting $DESC..."
    $0 stop
    sleep 1
    $0 start
    ;;
  status)
    if [ -f $PIDFILE ]; then
      PID=$(cat $PIDFILE)
      if kill -0 $PID 2>/dev/null; then
        echo "$DESC running in (pid $PID)"
      else
        echo "the pid file exists but the $DESC is not running"
      fi
    else
      echo "$DESC is not running ( no pid file )"
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

